<?php

class MudDalTraitsGeneratorLog extends MudDalTraitsGeneratorStandard {

  public function print_traits( $table, &$traits_list ) {

    $name = $table->get_name();

    $traits_name = 'MudDal_' . $name;

    $traits_list[] = $traits_name;

?>
trait <?= $traits_name ?> {

<?php

    $this->print_traits_log_get( $table );

    $this->print_traits_log_add( $table );

?>
}
<?php

  }

  function print_traits_log_get( $table ) {

    $tab_name = $table->get_name();
    $tab_const = $table->get_const();
    $function_name = "get_row_$tab_name";
    //$connection_type = $table->get_connection_type();
    $arg_list = [];

    foreach ( $table->col_map as $col ) {

      if ( ! $col->is_key() ) { continue; }

      $arg_type = $col->get_db_datatype();
      $arg_name = $col->get_prop();

      $arg = "{$arg_type} \${$arg_name}";

      $arg_list[] = $arg;

    }

    $args = implode( ', ', $arg_list );

    // 2022-02-21 jj5 - NEW:
    $get_function = "get_row";
    // 2022-02-21 jj5 - OLD:
    //$get_function = "get_row_$connection_type";

    $query = '[]';

?>

  public function <?= $function_name ?>( <?= $args ?> ) {

    // generated by <?= $this->get_generated_by( __FILE__, __LINE__ ) ?>

    return $this-><?= $get_function ?>(
      <?= $tab_const ?>,
      [
<?php

      foreach ( $table->col_map as $col ) :

      if ( ! $col->is_key() ) { continue; }

        $col_const = strtoupper( $col->get_name() );
        $arg_name = '$' . $col->get_prop();
?>
        <?= $col_const ?> => <?= $arg_name ?>,
<?php

      endforeach;

?>
      ]
    );

  }
<?php
  }

  function print_traits_log_add( $table ) {

    $function_name = "add_row_{$table->get_name()}";
    $arg_list = [];

    foreach ( $table->col_map as $col ) {

      if ( $col->is_vrt() ) { continue; }
      if ( $col->is_auto() ) { continue; }
      if ( $col->is_auto_inc() ) { continue; }

      $is_nullable = $col->get_nullable();
      $arg_type = $col->get_db_datatype();

      if ( $is_nullable || $col->is_interaction_id() ) {

        $arg_type = "?$arg_type";

      }

      $arg_name = $col->get_prop();

      $arg = "{$arg_type} \${$arg_name}";

      $default = $col->get_default();

      if ( $col->is_interaction_id() ) {

        $arg .= ' = null';

      }
      elseif ( $default === null && ! $is_nullable ) {

        // 2021-03-30 jj5 - in this case there is no default value

      }
      elseif ( $default === MUD_UNSPECIFIED ) {

        if ( $is_nullable ) {

          $arg .= ' = null';

        }
      }
      elseif ( $default === MUD_CURRENT_TIMESTAMP ) {

        // 2021-03-30 jj5 - THINK: do we ignore this? I think it's handled by the database.

      }
      else {

        $arg .= ' = ' . mud_json_compact( $default );

      }

      $arg_list[] = $arg;

    }

    $args = implode( ', ', $arg_list );

?>
  public function <?= $function_name ?>( <?= $args ?> ) {

    // generated by <?= $this->get_generated_by( __FILE__, __LINE__ ) ?>

<?php

      foreach ( $table->col_map as $col ) :

        if ( ! $col->is_interaction_id() ) { continue; }

        $interaction_prop = '$' . $col->get_prop();

?>
    if ( ! <?= $interaction_prop ?> ) { <?= $interaction_prop ?> = $this->get_interaction_id(); }

<?php

      endforeach;

      foreach ( $table->col_map as $col ) :

        if ( $col->is_auto_inc() ) { continue; }
        if ( $col->is_vrt() ) { continue; }
        if ( $col->is_auto() ) { continue; }

        $validation_function = 'validate_' . $col->get_name();

?>
    $this-><?= $validation_function ?>( $<?= $col->get_prop() ?> );
<?php

      endforeach;
?>

    $row = [
<?php

      $tab_const = strtoupper( $table->get_name() );
      $is_auto_inc = false;
      //$connection_type = $table->get_connection_type();

      foreach ( $table->col_map as $col ) :

        if ( $col->is_auto_inc() ) { $is_auto_inc = true; continue; }
        if ( $col->is_vrt() ) { continue; }
        if ( $col->is_auto() ) { continue; }

        $col_const = strtoupper( $col->get_name() );
        $arg_name = '$' . $col->get_prop();
?>
      <?= $col_const ?> => <?= $arg_name ?>,
<?php

      endforeach;

      $insert_function = ( $is_auto_inc ? 'insert_id' : 'insert' ); // . $connection_type;

?>
    ];

    return $this-><?= $insert_function ?>( <?= $tab_const ?>, $row );

  }
<?php
  }
}
