#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export MUDBALL_NAME='Mudball Web Framework';
export MUDBALL_CODE='mudball';

export MUDBALL_VERSION='0.6.1877';
export MUDBALL_VERSION_MAJOR='0';
export MUDBALL_VERSION_MINOR='6';
export MUDBALL_VERSION_PATCH='1877';

export MUDBALL_SVN_DATE='Date: 2025-09-16 06:52:03 +1000 (Tue, 16 Sep 2025)';
export MUDBALL_SVN_REVISION='Revision: 151680527';
export MUDBALL_SVN_AUTHOR='Author: jj5';

export MUDBALL_GIT_DATE='2025-09-16 06:52:03 +1000 (Tue, 16 Sep 2025)';
