#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export MUDBALL_NAME='Mudball Web Framework';
export MUDBALL_CODE='mudball';

export MUDBALL_VERSION='0.6.2067';
export MUDBALL_VERSION_MAJOR='0';
export MUDBALL_VERSION_MINOR='6';
export MUDBALL_VERSION_PATCH='2067';

export MUDBALL_SVN_DATE='Date: 2026-03-03 20:36:12 +1100 (Tue, 03 Mar 2026)';
export MUDBALL_SVN_REVISION='Revision: 151417520';
export MUDBALL_SVN_AUTHOR='Author: jj5';

export MUDBALL_GIT_DATE='2026-03-03 20:36:12 +1100 (Tue, 03 Mar 2026)';
