#!/bin/bash

# this file is automatically generated by kickass-libexec scripts...

export MUDBALL_NAME='Mudball Web Framework';
export MUDBALL_CODE='mudball';

export MUDBALL_VERSION='0.6.1635';
export MUDBALL_VERSION_MAJOR='0';
export MUDBALL_VERSION_MINOR='6';
export MUDBALL_VERSION_PATCH='1635';

export MUDBALL_SVN_DATE='Date: 2025-01-13 01:23:20 +1100 (Mon, 13 Jan 2025)';
export MUDBALL_SVN_REVISION='Revision: 58955206';
export MUDBALL_SVN_AUTHOR='Author: jj5';

export MUDBALL_GIT_DATE='2025-01-13 01:23:20 +1100 (Mon, 13 Jan 2025)';
