<?php

// this file is automatically generated by kickass-libexec scripts...

// you can change the name but not the code...
define( 'MUDBALL_NAME', 'Mudball Web Framework' );
define( 'MUDBALL_CODE', 'mudball' );

//define( 'MUDBALL_VERSION', '0.6.2013' );
define( 'MUDBALL_VERSION_MAJOR', 0 );
define( 'MUDBALL_VERSION_MINOR', 6 );
define( 'MUDBALL_VERSION_PATCH', 2013 );

define(
  'MUDBALL_SVN_DATE',
  '$Date: 2026-01-08 00:47:34 +1100 (Thu, 08 Jan 2026) $'
);
define( 'MUDBALL_SVN_REVISION', '$Revision: 119609925 $' );
define( 'MUDBALL_SVN_AUTHOR', '$Author: jj5 $' );

define( 'MUDBALL_GIT_DATE', '2026-01-08 00:47:34 +1100 (Thu, 08 Jan 2026)' );
